version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "3005:3005"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/projet
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  certificat-service:
    build: .
    command: node services/certificatMicroservice.js
    ports:
      - "50051:50051"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/projet
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: